from distutils.core import setup


setup(
    name='Flask-RESTBuilder',
    version='0.1.0',
    author='Srinivas Lade',
    author_email='srinulade1@gmail.com',
    packages=['flask_restbuilder'],
    description='Build REST APIs easily with autogenerated documentation',
    license='MIT',
)
